<a href="https://colab.research.google.com/github/mac-raj/TensorFlow/blob/main/TensorFlowBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

Tensor is a multi-dimensional array has an ability to run on GPU

**Import Dependencies**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

**Initialization of Tensors** 

In [3]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [6]:
y = tf.constant([[1,2,3],[5,6,7]])
print(y)

tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)


In [8]:
# Print a matrix which all element in one
ones_matrix = tf.ones((3,3),dtype=tf.int32)
print(ones_matrix)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [14]:
# Print a matrix which all element in zero
zeros_matrix = tf.zeros((2,3),dtype=tf.int32)
print(zeros_matrix)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [20]:
# Print a identity matrix
identity_matrix = tf.eye(3,dtype=tf.int32)
print(identity_matrix)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [25]:
# Print Strandard Normal Distribution
std_dist = tf.random.normal((3,3,4), mean=0, stddev=1)
print(std_dist)

tf.Tensor(
[[[ 0.72791606  0.500118    1.7360433   0.6376959 ]
  [-0.6210826  -0.06792945 -1.8213022   0.9962498 ]
  [-0.03924373  0.4160664   1.1299235  -1.17588   ]]

 [[ 0.29734656 -0.08943693  0.35503536  0.56801546]
  [ 0.311591   -0.0913387  -1.65483     0.05308809]
  [-0.0454025  -0.04583364  0.2294629   1.2324585 ]]

 [[ 0.21779545 -0.42113397  1.0567347   0.59836936]
  [-1.3208152   1.6089021  -0.18921922  0.52891606]
  [ 0.01737215 -0.01423121  0.31863365 -0.7729676 ]]], shape=(3, 3, 4), dtype=float32)


In [29]:
# Print Uniform Distribution
uniform_dist = tf.random.uniform((1,3), minval=0,maxval=1)
print(uniform_dist)

tf.Tensor([[0.7688142  0.8171598  0.38073158]], shape=(1, 3), dtype=float32)


In [34]:
# Print range 
range = tf.range(9)
print(range)
customized_range = tf.range(start=1, limit=10, delta =2)
print(customized_range)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [35]:
# Cast 
cast1 = tf.cast(range, dtype=tf.float32)
cast2 = tf.cast(customized_range, dtype=tf.float32)
print(cast1)
print(cast2)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8.], shape=(9,), dtype=float32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


**Mathematical Operations of Tensor**

In [45]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

# Additon
add = tf.add(x,y)
print(add)

# Subtraction
sub = tf.subtract(x,y)
print(sub)

# Multiplication
mul = tf.multiply(x,y)
print(mul)

# Division
div = tf.divide(x,y)
print(div)

# Dot Product
dot_product = tf.tensordot(x,y, axes=1)
print(dot_product)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor(32, shape=(), dtype=int32)


In [48]:
 # power of each element of matrix
 x1= tf.constant([1,3,7])
 x1= x1 ** 2
 print(x1)

tf.Tensor([ 1  9 49], shape=(3,), dtype=int32)


In [67]:
# Printing notation of tensor
x = tf.constant([1,4,56,7,8,3,78,90,12,4,6,8])
print(x[:])
print(x[2:])
print(x[:11])
print(x[2:4])
print(x[::3])
print(x[::-1])
print(x[::-2])

tf.Tensor([ 1  4 56  7  8  3 78 90 12  4  6  8], shape=(12,), dtype=int32)
tf.Tensor([56  7  8  3 78 90 12  4  6  8], shape=(10,), dtype=int32)
tf.Tensor([ 1  4 56  7  8  3 78 90 12  4  6], shape=(11,), dtype=int32)
tf.Tensor([56  7], shape=(2,), dtype=int32)
tf.Tensor([ 1  7 78  4], shape=(4,), dtype=int32)
tf.Tensor([ 8  6  4 12 90 78  3  8  7 56  4  1], shape=(12,), dtype=int32)
tf.Tensor([ 8  4 90  3  7  4], shape=(6,), dtype=int32)


In [59]:
#print index
indices = tf.constant([0,3])
x_index = tf.gather(x, indices)
print(x_index)

tf.Tensor([1 7], shape=(2,), dtype=int32)


In [66]:
mat = tf.constant([[1,2,3],[3,4,5],[4,7,9]])
print(mat[1,:])
print(mat[:,2])
print(mat[1,1:])

tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([3 5 9], shape=(3,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)


**Reshaping of Tensor**

In [69]:
# Reshape vector into matrix
x = tf.constant([1,4,56,7,8,3,78,90,12,4,6,8])
re_shape = tf.reshape(x,(4,3))
print(re_shape)

tf.Tensor(
[[ 1  4 56]
 [ 7  8  3]
 [78 90 12]
 [ 4  6  8]], shape=(4, 3), dtype=int32)


In [73]:
# Transpose matrix 
transpose = tf.transpose(re_shape)
print(transpose)

tf.Tensor(
[[ 1  7 78  4]
 [ 4  8 90  6]
 [56  3 12  8]], shape=(3, 4), dtype=int32)
